#!/usr/bin/env bash
set -euo pipefail

BASE_URL="${1:-http://localhost:8080}"
CLI_BIN="${CLI_BIN:-./bin/agenthub-cli}"
PLUGIN_BIN="${PLUGIN_BIN:-./plugins/agenthub-connector-plugin/bin/agenthub-plugin.mjs}"
PASS=0
FAIL=0
BASE_HOST="$(printf '%s' "$BASE_URL" | sed -E 's#^[a-zA-Z]+://([^/:]+).*$#\1#')"
CURL_PROXY_BYPASS=()

if [[ "$BASE_HOST" == "localhost" || "$BASE_HOST" == "127.0.0.1" || "$BASE_HOST" == "::1" ]]; then
  CURL_PROXY_BYPASS=(--noproxy "*")
fi

WORKDIR="$(mktemp -d)"
USER_COOKIE_JAR="$WORKDIR/user.cookies"
ADMIN_COOKIE_JAR="$WORKDIR/admin.cookies"
ADMIN_USERNAME="${BOOTSTRAP_ADMIN_USERNAME:-admin}"
ADMIN_PASSWORD="${BOOTSTRAP_ADMIN_PASSWORD:-Admin@staging2026}"
NAMESPACE_SLUG="ahub-$(date +%s)"
LABEL_SLUG="agenthub-smoke-$(date +%s)"

cleanup() {
  rm -rf "$WORKDIR"
}
trap cleanup EXIT

curl_base() {
  curl "${CURL_PROXY_BYPASS[@]}" "$@"
}

json_get() {
  local json="$1"
  local path="$2"
  printf '%s' "$json" | node -e '
    const fs = require("fs");
    const input = fs.readFileSync(0, "utf8");
    const obj = JSON.parse(input);
    const path = process.argv[1].split(".");
    let cur = obj;
    for (const part of path) {
      if (!part) continue;
      if (cur == null) {
        process.exit(2);
      }
      if (/^\d+$/.test(part)) {
        cur = cur[Number(part)];
      } else {
        cur = cur[part];
      }
    }
    if (cur === undefined) {
      process.exit(2);
    }
    if (typeof cur === "object") {
      process.stdout.write(JSON.stringify(cur));
    } else {
      process.stdout.write(String(cur));
    }
  ' "$path"
}

assert_eq() {
  local desc="$1"
  local actual="$2"
  local expected="$3"
  if [[ "$actual" == "$expected" ]]; then
    echo "PASS: $desc"
    PASS=$((PASS + 1))
  else
    echo "FAIL: $desc (expected '$expected', got '$actual')"
    FAIL=$((FAIL + 1))
  fi
}

assert_contains() {
  local desc="$1"
  local haystack="$2"
  local needle="$3"
  if [[ "$haystack" == *"$needle"* ]]; then
    echo "PASS: $desc"
    PASS=$((PASS + 1))
  else
    echo "FAIL: $desc (missing '$needle')"
    FAIL=$((FAIL + 1))
  fi
}

assert_file_nonempty() {
  local desc="$1"
  local file_path="$2"
  if [[ -s "$file_path" ]]; then
    echo "PASS: $desc"
    PASS=$((PASS + 1))
  else
    echo "FAIL: $desc (file missing or empty: $file_path)"
    FAIL=$((FAIL + 1))
  fi
}

fetch_csrf_token() {
  local cookie_jar="$1"
  curl_base -s -b "$cookie_jar" -c "$cookie_jar" "$BASE_URL/api/v1/auth/me" >/dev/null
  awk '$6 == "XSRF-TOKEN" { print $7 }' "$cookie_jar" | tail -n 1
}

api_json() {
  local method="$1"
  local url="$2"
  local cookie_jar="$3"
  local csrf_token="$4"
  local body="$5"
  local response=""
  local attempt
  for attempt in $(seq 1 6); do
    response="$(curl_base --max-time 20 -sS \
      -X "$method" "$url" \
      -b "$cookie_jar" \
      -c "$cookie_jar" \
      -H "X-XSRF-TOKEN: $csrf_token" \
      -H "Content-Type: application/json" \
      -d "$body")"
    if [[ "$response" != *"\"code\":429"* ]]; then
      printf '%s' "$response"
      return 0
    fi
    sleep "$attempt"
  done
  printf '%s' "$response"
}

create_skill_zip() {
  local output_zip="$1"
  local name="$2"
  local description="$3"
  local version="$4"
  local extra_frontmatter="${5:-}"
  local pkg_dir="$WORKDIR/$(basename "$output_zip" .zip)"
  mkdir -p "$pkg_dir"
  cat >"$pkg_dir/SKILL.md" <<EOF
---
name: $name
description: $description
version: $version
$extra_frontmatter---

# $name

Generated by enterprise AgentHub smoke test.
EOF
  cat >"$pkg_dir/README.md" <<EOF
# $name

Generated by enterprise AgentHub smoke test.
EOF
  (cd "$pkg_dir" && zip -q -r "$output_zip" SKILL.md README.md)
}

publish_skill() {
  local namespace_slug="$1"
  local cookie_jar="$2"
  local csrf_token="$3"
  local zip_path="$4"
  curl_base --max-time 60 -sS \
    -X POST "$BASE_URL/api/v1/skills/$namespace_slug/publish" \
    -b "$cookie_jar" \
    -c "$cookie_jar" \
    -H "X-XSRF-TOKEN: $csrf_token" \
    -F "file=@$zip_path;type=application/zip" \
    -F "visibility=PUBLIC" \
    -F "confirmWarnings=true"
}

wait_for_search_hit() {
  local expected_slug="$1"
  local query_string="$2"
  local cookie_jar="${3:-}"
  for attempt in $(seq 1 20); do
    local response
    if [[ -n "$cookie_jar" ]]; then
      response="$(curl_base --max-time 20 -sS -b "$cookie_jar" "$BASE_URL/api/v1/search/skills?$query_string")"
    else
      response="$(curl_base --max-time 20 -sS "$BASE_URL/api/v1/search/skills?$query_string")"
    fi
    if printf '%s' "$response" | grep -q "\"slug\":\"$expected_slug\""; then
      return 0
    fi
    sleep "$attempt"
  done
  return 1
}

echo "=== Enterprise AgentHub Smoke Test ==="
echo "Target: $BASE_URL"
echo "Workspace: $WORKDIR"
echo

ADMIN_CSRF="$(fetch_csrf_token "$ADMIN_COOKIE_JAR")"
ADMIN_LOGIN_RESPONSE="$(api_json POST "$BASE_URL/api/v1/auth/local/login" "$ADMIN_COOKIE_JAR" "$ADMIN_CSRF" "{\"username\":\"$ADMIN_USERNAME\",\"password\":\"$ADMIN_PASSWORD\"}")"
assert_contains "Bootstrap admin login" "$ADMIN_LOGIN_RESPONSE" "\"code\":0"
ADMIN_CSRF="$(fetch_csrf_token "$ADMIN_COOKIE_JAR")"

CREATE_NS_RESPONSE="$(api_json POST "$BASE_URL/api/v1/namespaces" "$ADMIN_COOKIE_JAR" "$ADMIN_CSRF" "{\"slug\":\"$NAMESPACE_SLUG\",\"displayName\":\"Enterprise $NAMESPACE_SLUG\",\"description\":\"enterprise smoke\"}")"
NAMESPACE_CODE="$(json_get "$CREATE_NS_RESPONSE" "code")"
assert_eq "Admin creates team namespace" "$NAMESPACE_CODE" "0"
ACTOR_COOKIE_JAR="$ADMIN_COOKIE_JAR"
ACTOR_CSRF="$ADMIN_CSRF"

TARGET_ZIP="$WORKDIR/payment-base.zip"
SOURCE_ZIP="$WORKDIR/payment-service.zip"
CLI_ZIP="$WORKDIR/agent-cli-skill.zip"
CLI_CATALOG_FILE="$WORKDIR/cli-catalog.json"
CLI_RELATIONS_FILE="$WORKDIR/cli-relations.json"
DOWNLOAD_FILE="$WORKDIR/downloaded-skill.zip"
PLUGIN_CONTEXT_FILE="$WORKDIR/plugin-context.json"
PLUGIN_TARGET_DIR="$WORKDIR/plugin-workspace/.claude/skills"

create_skill_zip "$TARGET_ZIP" "Payment Base Skill" "payment related target skill" "1.0.0" $'x-agenthub-asset-type: integration\nx-agenthub-domain: payment\nx-agenthub-stage: develop\nx-agenthub-topology: bff\nx-agenthub-stack:\n  - spring-boot3\n  - maven\nx-agenthub-owner-team: payments-platform\nx-agenthub-keywords:\n  - gateway\nx-agenthub-maintenance-mode: agent\n'
create_skill_zip "$SOURCE_ZIP" "Payment Service Skill" "legacy package without catalog metadata" "1.0.0"
create_skill_zip "$CLI_ZIP" "Agent CLI Skill" "published through agenthub-cli" "1.0.0"

TARGET_PUBLISH_RESPONSE="$(publish_skill "$NAMESPACE_SLUG" "$ACTOR_COOKIE_JAR" "$ACTOR_CSRF" "$TARGET_ZIP")"
TARGET_SLUG="$(json_get "$TARGET_PUBLISH_RESPONSE" "data.slug")"
assert_contains "Publish target skill" "$TARGET_PUBLISH_RESPONSE" "\"code\":0"

SOURCE_PUBLISH_RESPONSE="$(publish_skill "$NAMESPACE_SLUG" "$ACTOR_COOKIE_JAR" "$ACTOR_CSRF" "$SOURCE_ZIP")"
SOURCE_SLUG="$(json_get "$SOURCE_PUBLISH_RESPONSE" "data.slug")"
assert_contains "Publish legacy source skill" "$SOURCE_PUBLISH_RESPONSE" "\"code\":0"

SOURCE_CATALOG_BODY="$(cat <<EOF
{"assetType":"microservice","domain":"payment","stage":"develop","topology":"bff","stack":["spring-boot3","maven"],"ownerTeam":"payments-domain","keywords":["checkout","gateway"],"maintenanceMode":"agent","relations":[]}
EOF
)"
SOURCE_CATALOG_RESPONSE="$(api_json PUT "$BASE_URL/api/v1/skills/$NAMESPACE_SLUG/$SOURCE_SLUG/catalog" "$ACTOR_COOKIE_JAR" "$ACTOR_CSRF" "$SOURCE_CATALOG_BODY")"
SOURCE_ASSET_TYPE="$(json_get "$SOURCE_CATALOG_RESPONSE" "data.assetType")"
assert_eq "Write catalog overlay for legacy skill" "$SOURCE_ASSET_TYPE" "microservice"

RELATIONS_BODY="$(cat <<EOF
{"relations":[{"type":"recommendedWith","target":"@$NAMESPACE_SLUG/$TARGET_SLUG","title":"Payment Base Skill","note":"shared payment context"}]}
EOF
)"
RELATIONS_RESPONSE="$(api_json PUT "$BASE_URL/api/v1/skills/$NAMESPACE_SLUG/$SOURCE_SLUG/relations" "$ACTOR_COOKIE_JAR" "$ACTOR_CSRF" "$RELATIONS_BODY")"
RELATION_TARGET="$(json_get "$RELATIONS_RESPONSE" "data.0.target")"
assert_eq "Write related skill graph" "$RELATION_TARGET" "@$NAMESPACE_SLUG/$TARGET_SLUG"

DETAIL_RESPONSE="$(curl_base --max-time 20 -sS -b "$ACTOR_COOKIE_JAR" "$BASE_URL/api/v1/skills/$NAMESPACE_SLUG/$SOURCE_SLUG")"
DETAIL_ASSET_TYPE="$(json_get "$DETAIL_RESPONSE" "data.catalogProfile.assetType")"
DETAIL_RELATED_RESOLVED="$(json_get "$DETAIL_RESPONSE" "data.relatedSkills.0.resolved")"
assert_eq "Detail returns catalog profile" "$DETAIL_ASSET_TYPE" "microservice"
assert_eq "Detail returns resolved related skill" "$DETAIL_RELATED_RESOLVED" "true"

SEARCH_QUERY="q=&assetType=microservice&domain=payment&stage=develop&topology=bff&stack=spring-boot3&sort=recommended&page=0&size=20"
if wait_for_search_hit "$SOURCE_SLUG" "$SEARCH_QUERY" "$ACTOR_COOKIE_JAR"; then
  echo "PASS: Search returns filtered enterprise asset"
  PASS=$((PASS + 1))
else
  echo "FAIL: Search returns filtered enterprise asset"
  FAIL=$((FAIL + 1))
fi

RECOMMEND_RESPONSE="$(curl_base --max-time 20 -sS -b "$ACTOR_COOKIE_JAR" "$BASE_URL/api/v1/skills/$NAMESPACE_SLUG/$SOURCE_SLUG/recommendations")"
RECOMMEND_TARGET_SLUG="$(json_get "$RECOMMEND_RESPONSE" "data.0.slug")"
RECOMMEND_REASON_STRING="$(json_get "$RECOMMEND_RESPONSE" "data.0.reasons")"
assert_eq "Skill recommendation hits related target" "$RECOMMEND_TARGET_SLUG" "$TARGET_SLUG"
assert_contains "Recommendation reason includes graph/domain signal" "$RECOMMEND_REASON_STRING" "related-by-graph"

CONTEXT_RECOMMEND_RESPONSE="$(api_json POST "$BASE_URL/api/v1/recommendations/context" "$ACTOR_COOKIE_JAR" "$ACTOR_CSRF" '{"assetType":"microservice","domain":"payment","stage":"develop","topology":"bff","stack":["spring-boot3","maven"],"keywords":["gateway"],"namespace":"'"$NAMESPACE_SLUG"'"}')"
assert_contains "Context recommendation returns payment-related skill" "$CONTEXT_RECOMMEND_RESPONSE" "\"code\":0"
assert_contains "Context recommendation contains namespace skill" "$CONTEXT_RECOMMEND_RESPONSE" "\"namespace\":\"$NAMESPACE_SLUG\""

LABEL_CREATE_RESPONSE="$(api_json POST "$BASE_URL/api/v1/admin/labels" "$ADMIN_COOKIE_JAR" "$ADMIN_CSRF" "{\"slug\":\"$LABEL_SLUG\",\"type\":\"RECOMMENDED\",\"visibleInFilter\":true,\"sortOrder\":42,\"translations\":[{\"locale\":\"en\",\"displayName\":\"Agent Smoke Label\"}]}")"
assert_contains "Create visible label definition" "$LABEL_CREATE_RESPONSE" "\"code\":0"

TOKEN_CREATE_RESPONSE="$(api_json POST "$BASE_URL/api/v1/tokens" "$ACTOR_COOKIE_JAR" "$ACTOR_CSRF" '{"name":"agenthub-smoke-token","scopes":["skill:read","skill:publish","skill:delete","token:manage"],"expiresAt":null}')"
API_TOKEN="$(json_get "$TOKEN_CREATE_RESPONSE" "data.token")"
assert_contains "Create API token for CLI" "$API_TOKEN" "sk_"

AGENT_PROFILE_RESPONSE="$(curl_base --max-time 20 -sS "$BASE_URL/api/v1/agent/profile")"
assert_contains "Agent profile endpoint returns platform identity" "$AGENT_PROFILE_RESPONSE" "\"platformName\":\"agenthub-enterprise\""

cat >"$PLUGIN_CONTEXT_FILE" <<EOF
{
  "workspaceName": "payment-service",
  "language": "java",
  "framework": "spring-boot3",
  "newProject": false,
  "assetType": "microservice",
  "domain": "payment",
  "stage": "develop",
  "topology": "bff",
  "stack": ["spring-boot3", "maven"],
  "keywords": ["gateway"],
  "namespace": "$NAMESPACE_SLUG"
}
EOF

AGENT_INSTALL_PLAN_RESPONSE="$(AGENTHUB_BASE_URL="$BASE_URL" AGENTHUB_TOKEN="$API_TOKEN" "$CLI_BIN" agent install-plan --context-file "$PLUGIN_CONTEXT_FILE" --json)"
assert_contains "CLI agent install plan returns required payment skill" "$AGENT_INSTALL_PLAN_RESPONSE" "\"slug\": \"$SOURCE_SLUG\""

PLUGIN_PROFILE_OUTPUT="$(AGENTHUB_BASE_URL="$BASE_URL" AGENTHUB_TOKEN="$API_TOKEN" node "$PLUGIN_BIN" profile)"
assert_contains "Local Claude plugin reads platform profile" "$PLUGIN_PROFILE_OUTPUT" "\"platformName\": \"agenthub-enterprise\""

PLUGIN_PLAN_OUTPUT="$(AGENTHUB_BASE_URL="$BASE_URL" AGENTHUB_TOKEN="$API_TOKEN" node "$PLUGIN_BIN" install-plan --context-file "$PLUGIN_CONTEXT_FILE")"
assert_contains "Local Claude plugin returns install plan" "$PLUGIN_PLAN_OUTPUT" "\"slug\": \"$SOURCE_SLUG\""

PLUGIN_INSTALL_OUTPUT="$(AGENTHUB_BASE_URL="$BASE_URL" AGENTHUB_TOKEN="$API_TOKEN" node "$PLUGIN_BIN" install-skill --skill "@$NAMESPACE_SLUG/$SOURCE_SLUG" --target "$PLUGIN_TARGET_DIR")"
assert_contains "Local Claude plugin installs target skill" "$PLUGIN_INSTALL_OUTPUT" "\"coordinate\": \"@$NAMESPACE_SLUG/$SOURCE_SLUG\""
assert_file_nonempty "Local Claude plugin unpacks SKILL.md" "$PLUGIN_TARGET_DIR/$NAMESPACE_SLUG--$SOURCE_SLUG/SKILL.md"

cat >"$CLI_CATALOG_FILE" <<EOF
{
  "assetType": "business",
  "domain": "order",
  "stage": "test",
  "topology": "batch",
  "stack": ["java21", "maven"],
  "ownerTeam": "agent-ops",
  "keywords": ["fulfillment", "billing"],
  "maintenanceMode": "agent",
  "relations": []
}
EOF

CLI_PUBLISH_OUTPUT="$(AGENTHUB_BASE_URL="$BASE_URL" AGENTHUB_TOKEN="$API_TOKEN" "$CLI_BIN" publish --namespace "$NAMESPACE_SLUG" --file "$CLI_ZIP" --catalog-file "$CLI_CATALOG_FILE" --yes)"
CLI_SLUG="$(json_get "$CLI_PUBLISH_OUTPUT" "slug")"
assert_eq "CLI publish succeeds" "$CLI_SLUG" "agent-cli-skill"

CLI_SEARCH_OUTPUT="$(AGENTHUB_BASE_URL="$BASE_URL" AGENTHUB_TOKEN="$API_TOKEN" "$CLI_BIN" search --assetType business --domain order --json)"
assert_contains "CLI search hits business asset" "$CLI_SEARCH_OUTPUT" "\"slug\": \"$CLI_SLUG\""

CLI_INSPECT_OUTPUT="$(AGENTHUB_BASE_URL="$BASE_URL" AGENTHUB_TOKEN="$API_TOKEN" "$CLI_BIN" inspect --skill "@$NAMESPACE_SLUG/$CLI_SLUG" --json)"
assert_contains "CLI inspect returns skill detail" "$CLI_INSPECT_OUTPUT" "\"slug\": \"$CLI_SLUG\""

CLI_CATALOG_GET_OUTPUT="$(AGENTHUB_BASE_URL="$BASE_URL" AGENTHUB_TOKEN="$API_TOKEN" "$CLI_BIN" catalog get --skill "@$NAMESPACE_SLUG/$CLI_SLUG" --json)"
assert_contains "CLI catalog get returns asset type" "$CLI_CATALOG_GET_OUTPUT" "\"assetType\": \"business\""

cat >"$CLI_CATALOG_FILE" <<EOF
{
  "assetType": "business",
  "domain": "order",
  "stage": "release",
  "topology": "batch",
  "stack": ["java21", "maven", "harness"],
  "ownerTeam": "agent-ops-updated",
  "keywords": ["fulfillment", "billing", "release"],
  "maintenanceMode": "agent",
  "relations": []
}
EOF
CLI_CATALOG_SET_OUTPUT="$(AGENTHUB_BASE_URL="$BASE_URL" AGENTHUB_TOKEN="$API_TOKEN" "$CLI_BIN" catalog set --skill "@$NAMESPACE_SLUG/$CLI_SLUG" --file "$CLI_CATALOG_FILE")"
assert_contains "CLI catalog set updates owner team" "$CLI_CATALOG_SET_OUTPUT" "\"ownerTeam\": \"agent-ops-updated\""

cat >"$CLI_RELATIONS_FILE" <<EOF
{
  "relations": [
    {
      "type": "recommendedWith",
      "target": "@$NAMESPACE_SLUG/$TARGET_SLUG",
      "title": "Payment Base Skill",
      "note": "connected by cli smoke"
    }
  ]
}
EOF
CLI_RELATIONS_OUTPUT="$(AGENTHUB_BASE_URL="$BASE_URL" AGENTHUB_TOKEN="$API_TOKEN" "$CLI_BIN" relations sync --skill "@$NAMESPACE_SLUG/$CLI_SLUG" --file "$CLI_RELATIONS_FILE")"
assert_contains "CLI relations sync writes relation target" "$CLI_RELATIONS_OUTPUT" "\"target\": \"@$NAMESPACE_SLUG/$TARGET_SLUG\""

CLI_LABEL_ADD_OUTPUT="$(AGENTHUB_BASE_URL="$BASE_URL" AGENTHUB_TOKEN="$API_TOKEN" "$CLI_BIN" labels add --skill "@$NAMESPACE_SLUG/$CLI_SLUG" --label "$LABEL_SLUG")"
assert_contains "CLI labels add succeeds" "$CLI_LABEL_ADD_OUTPUT" "\"slug\": \"$LABEL_SLUG\""

CLI_LABEL_LIST_OUTPUT="$(AGENTHUB_BASE_URL="$BASE_URL" AGENTHUB_TOKEN="$API_TOKEN" "$CLI_BIN" labels list --skill "@$NAMESPACE_SLUG/$CLI_SLUG" --json)"
assert_contains "CLI labels list shows attached label" "$CLI_LABEL_LIST_OUTPUT" "\"slug\": \"$LABEL_SLUG\""

CLI_LABEL_REMOVE_OUTPUT="$(AGENTHUB_BASE_URL="$BASE_URL" AGENTHUB_TOKEN="$API_TOKEN" "$CLI_BIN" labels remove --skill "@$NAMESPACE_SLUG/$CLI_SLUG" --label "$LABEL_SLUG")"
assert_contains "CLI labels remove succeeds" "$CLI_LABEL_REMOVE_OUTPUT" "\"message\": \"Label detached\""

CLI_RECOMMEND_SKILL_OUTPUT="$(AGENTHUB_BASE_URL="$BASE_URL" AGENTHUB_TOKEN="$API_TOKEN" "$CLI_BIN" recommend --skill "@$NAMESPACE_SLUG/$CLI_SLUG" --json)"
assert_contains "CLI skill recommendation returns related target" "$CLI_RECOMMEND_SKILL_OUTPUT" "\"slug\": \"$TARGET_SLUG\""

CLI_RECOMMEND_CONTEXT_OUTPUT="$(AGENTHUB_BASE_URL="$BASE_URL" AGENTHUB_TOKEN="$API_TOKEN" "$CLI_BIN" recommend --assetType microservice --domain payment --stage develop --topology bff --stack spring-boot3,maven --json)"
assert_contains "CLI context recommendation returns candidate list" "$CLI_RECOMMEND_CONTEXT_OUTPUT" "\"namespace\": \"$NAMESPACE_SLUG\""

AGENTHUB_BASE_URL="$BASE_URL" AGENTHUB_TOKEN="$API_TOKEN" "$CLI_BIN" download --skill "@$NAMESPACE_SLUG/$CLI_SLUG" --out "$DOWNLOAD_FILE" >/dev/null
assert_file_nonempty "CLI download writes bundle to disk" "$DOWNLOAD_FILE"

echo
echo "Results: $PASS passed, $FAIL failed"
if [[ "$FAIL" -ne 0 ]]; then
  exit 1
fi
